# ===== Erros - Falhas genericas =======
ERRO.FG.001_ERRO_INESPERADO=Ocorreu um erro interno inesperado no sistema. Tente novamente mais tarde.
ERRO.FG.002_CORPO_REQUISICAO_INVALIDO=O corpo da requisicao e invalido.
ERRO.FG.003_PARAMETRO_INVALIDO=O parametro '%s' recebeu o valor '%s', que e invalido para o tipo %s.
ERRO.FG.004_RECURSO_INEXISTENTE=O recurso solicitado nao foi encontrado.
ERRO.FG.005_PROPRIEDADE_INEXISTENTE=A propriedade '%s' nao existe.

# ===== Erros - Regras de Negocio para Credito =======
ERRO.RN.CREDITO_001_NUMERO_NFSE_NAO_INFORMADO=O parametro 'numeroNfse' nao foi informado.
ERRO.RN.CREDITO_002_NUMERO_CREDITO_NAO_INFORMADO=O parametro 'numeroCredito' nao foi informado.
ERRO.RN.CREDITO_NAO_ENCONTRADO=Credito constituido nao encontrado.

# ===== Erros - Regras de Negocio para API Key =======
ERRO.RN.API_KEY_NAO_ENCONTRADA=API Key nao encontrada.
ERRO.RN.API_KEY_JA_REVOGADA=Esta API Key ja foi revogada.
