package br.com.builders.basecliente.domain.exception;

import lombok.Getter;

@Getter
public enum CodigoMensagem {

    // ===== Erros - Falhas genéricas =======
    FG_001_ERRO_INESPERADO("ERRO.FG.001_ERRO_INESPERADO"),
    FG_002_CORPO_REQUISICAO_INVALIDO("ERRO.FG.002_CORPO_REQUISICAO_INVALIDO"),
    FG_003_PARAMETRO_INVALIDO("ERRO.FG.003_PARAMETRO_INVALIDO"),
    FG_004_RECURSO_INEXISTENTE("ERRO.FG.004_RECURSO_INEXISTENTE"),
    FG_005_PROPRIEDADE_INEXISTENTE("ERRO.FG.005_PROPRIEDADE_INEXISTENTE"),

    // ===== Erros - regras de negócio genericas =======
    RN_001_DOCUMENTO_VAZIO("ERRO.RN.001_DOCUMENTO_VAZIO"),
    RN_002_DOCUMENTO_INVALIDO("ERRO.RN.002_DOCUMENTO_INVALIDO"),
    RN_003_DOCUMENTO_NAO_ENCONTRADO("ERRO.RN.003_DOCUMENTO_NAO_ENCONTRADO"),
    RN_004_CODIGO_NAO_ENCONTRADO("ERRO.RN.004_CODIGO_NAO_ENCONTRADO"),
    RN_005_CODIGO_NAO_INFORMADO("ERRO.RN.005_CODIGO_NAO_INFORMADO"),

    // ===== Erros - Customer =======
    RN_CUSTOMER_001_NAME_VAZIO("ERRO.RN.CUSTOMER_001_NAME_VAZIO"),
    RN_CUSTOMER_002_BIRTH_DATE_VAZIO("ERRO.RN.CUSTOMER_002_BIRTH_DATE_VAZIO"),
    RN_CUSTOMER_003_CUSTOMER_EXISTENTE_DOCUMENTO("ERRO.RN.CUSTOMER_003_CUSTOMER_EXISTENTE_DOCUMENTO");


    private String value;

    CodigoMensagem(String value) {
        this.value = value;
    }
}
